const Author = [
  {
    name: "Shaykh Khalid al-Hibsh",
    background: "http://jgnatch-dropshare.s3.amazonaws.com/Screen-Shot-2016-03-01-15-29-06/Screen-Shot-2016-03-01-15-29-06.png",
    songs: [
      {
        title: "General Ruqya",
        length: '4031',
        album: "Shaykh Khalid al-Hibsh",
        albumImage: "http://www.clashmusic.com/sites/default/files/field/image/Breakbot%20%20Still%20Waters.jpg",
        url: "https://s3.eu-central-1.amazonaws.com/ruqyah/roqya.mp3",
      },
      {
        title: "Evil Eye (AYN)",
        length: '5591',
        album: "Shaykh Khalid al-Hibsh",
        albumImage: "http://images.junostatic.com/full/CS2032801-02A-BIG.jpg",
        url: "https://s3.eu-central-1.amazonaws.com/ruqyah/eyehasd.mp3",
      },
      {
        title: "Black Magic (SIHR)",
        length: '5603',
        album: "Shaykh Khalid al-Hibsh",
        albumImage: "https://edbangerla.files.wordpress.com/2013/07/artworks-000052534531-4p2uyd-t500x500.jpg",
        url: "https://s3.eu-central-1.amazonaws.com/ruqyah/sihr.mp3",
      },
      {
        title: "Knowledge (ILM)",
        length: '5681',
        album: "Shaykh Khalid al-Hibsh",
        albumImage: "https://fanart.tv/fanart/music/eb6de5f6-98f8-4b5a-bfdc-f87fa4936baa/artistbackground/-4f70ac2a1f207.jpg",
        url: "https://s3.eu-central-1.amazonaws.com/ruqyah/alelm.mp3",
      },
      {
        title: "Advice (NASEEHA)",
        length: '3756',
        album: "Shaykh Khalid al-Hibsh",
        albumImage: "https://upload.wikimedia.org/wikipedia/en/4/48/Pnau_alternate_cover.jpg",
        url: "https://s3.eu-central-1.amazonaws.com/ruqyah/nasiha.mp3",
      },
      {
        title: "Burning (HARQ)",
        length: '2724',
        album: "Shaykh Khalid al-Hibsh",
        albumImage: "https://upload.wikimedia.org/wikipedia/en/4/48/Pnau_alternate_cover.jpg",
        url: "https://s3.eu-central-1.amazonaws.com/ruqyah/harq.mp3",
      },
      {
        title: "Healing (SHIFA')",
        length: '2889',
        album: "Shaykh Khalid al-Hibsh",
        albumImage: "https://upload.wikimedia.org/wikipedia/en/4/48/Pnau_alternate_cover.jpg",
        url: "https://s3.eu-central-1.amazonaws.com/ruqyah/shifa.mp3",
      },
      {
        title: "Adultery / Fornication (ZINA)",
        length: '3894',
        album: "Shaykh Khalid al-Hibsh",
        albumImage: "https://upload.wikimedia.org/wikipedia/en/4/48/Pnau_alternate_cover.jpg",
        url: "https://s3.eu-central-1.amazonaws.com/ruqyah/zina.mp3",
      },
      {
        title: "Summarised Ruqya (MOKHTASAR)",
        length: '1377',
        album: "Shaykh Khalid al-Hibsh",
        albumImage: "https://upload.wikimedia.org/wikipedia/en/4/48/Pnau_alternate_cover.jpg",
        url: "https://s3.eu-central-1.amazonaws.com/ruqyah/mokhtsra.mp3",
      },
      {
        title: "Divorce (TALAQ)",
        length: '5605',
        album: "Shaykh Khalid al-Hibsh",
        albumImage: "https://upload.wikimedia.org/wikipedia/en/4/48/Pnau_alternate_cover.jpg",
        url: "https://s3.eu-central-1.amazonaws.com/ruqyah/talaq.mp3",
      },
      {
        title: "Destruction (TADMEER)",
        length: '5684',
        album: "Shaykh Khalid al-Hibsh",
        albumImage: "https://upload.wikimedia.org/wikipedia/en/4/48/Pnau_alternate_cover.jpg",
        url: "https://s3.eu-central-1.amazonaws.com/ruqyah/tadmer.mp3",
      },
      {
        title: "Surat Al-Falaq & Surat An-Naas",
        length: '167',
        album: "Shaykh Khalid al-Hibsh",
        albumImage: "https://upload.wikimedia.org/wikipedia/en/4/48/Pnau_alternate_cover.jpg",
        url: "https://s3.eu-central-1.amazonaws.com/ruqyah/falaqnas.mp3",
      },
      {
        title: "Ayat-Al-Kursi",
        length: '101',
        album: "Shaykh Khalid al-Hibsh",
        albumImage: "https://upload.wikimedia.org/wikipedia/en/4/48/Pnau_alternate_cover.jpg",
        url: "https://s3.eu-central-1.amazonaws.com/ruqyah/kursi.mp3",
      },
      {
        title: "Prayers upon the Prophet ﷺ",
        length: '61',
        album: "Shaykh Khalid al-Hibsh",
        albumImage: "https://upload.wikimedia.org/wikipedia/en/4/48/Pnau_alternate_cover.jpg",
        url: "https://s3.eu-central-1.amazonaws.com/ruqyah/salat.mp3",
      },
      {
        title: "Jews (YAHOOD)",
        length: '5766',
        album: "Shaykh Khalid al-Hibsh",
        albumImage: "https://upload.wikimedia.org/wikipedia/en/4/48/Pnau_alternate_cover.jpg",
        url: "https://s3.eu-central-1.amazonaws.com/ruqyah/yahod.mp3",
      },
      {
        title: "Christians (NASAARAH)",
        length: '3371',
        album: "Shaykh Khalid al-Hibsh",
        albumImage: "https://upload.wikimedia.org/wikipedia/en/4/48/Pnau_alternate_cover.jpg",
        url: "https://s3.eu-central-1.amazonaws.com/ruqyah/nasara.mp3",
      },
      {
        title: "Surat As-Saafat",
        length: '1360',
        album: "Shaykh Khalid al-Hibsh",
        albumImage: "https://upload.wikimedia.org/wikipedia/en/4/48/Pnau_alternate_cover.jpg",
        url: "https://s3.eu-central-1.amazonaws.com/ruqyah/safat.mp3",
      },
      {
        title: "Surat Al-Jinn",
        length: '302',
        album: "Shaykh Khalid al-Hibsh",
        albumImage: "https://upload.wikimedia.org/wikipedia/en/4/48/Pnau_alternate_cover.jpg",
        url: "https://s3.eu-central-1.amazonaws.com/ruqyah/jin.mp3",
      },
      {
        title: "Surat Yaseen",
        length: '1063',
        album: "Shaykh Khalid al-Hibsh",
        albumImage: "https://upload.wikimedia.org/wikipedia/en/4/48/Pnau_alternate_cover.jpg",
        url: "https://s3.eu-central-1.amazonaws.com/ruqyah/yaseen.mp3",
      },
      {
        title: "Birds (AT-TUYUUR)",
        length: '1520',
        album: "Shaykh Khalid al-Hibsh",
        albumImage: "https://upload.wikimedia.org/wikipedia/en/4/48/Pnau_alternate_cover.jpg",
        url: "https://s3.eu-central-1.amazonaws.com/ruqyah/bird.mp3",
      },
      {
        title: "Provisions (RIZQ)",
        length: '2953',
        album: "Shaykh Khalid al-Hibsh",
        albumImage: "https://upload.wikimedia.org/wikipedia/en/4/48/Pnau_alternate_cover.jpg",
        url: "https://s3.eu-central-1.amazonaws.com/ruqyah/RIZQ+1.mp3",
      },
      {
        title: "Mountains (AL-JIBAAL)",
        length: '1211',
        album: "Shaykh Khalid al-Hibsh",
        albumImage: "https://upload.wikimedia.org/wikipedia/en/4/48/Pnau_alternate_cover.jpg",
        url: "https://s3.eu-central-1.amazonaws.com/ruqyah/jibal.mp3",
      },
      {
        title: "Guidance & Repentance",
        length: '2834',
        album: "Shaykh Khalid al-Hibsh",
        albumImage: "https://upload.wikimedia.org/wikipedia/en/4/48/Pnau_alternate_cover.jpg",
        url: "https://s3.eu-central-1.amazonaws.com/ruqyah/hidaya.mp3",
      },
      {
        title: "Ruqya for Hair Loss",
        length: '2430',
        album: "Shaykh Khalid al-Hibsh",
        albumImage: "https://upload.wikimedia.org/wikipedia/en/4/48/Pnau_alternate_cover.jpg",
        url: "https://s3.eu-central-1.amazonaws.com/ruqyah/shaar.mp3",
      },
      {
        title: "Surat Al-Fatihah",
        length: '220',
        album: "Shaykh Khalid al-Hibsh",
        albumImage: "https://upload.wikimedia.org/wikipedia/en/4/48/Pnau_alternate_cover.jpg",
        url: "https://s3.eu-central-1.amazonaws.com/ruqyah/fatha.mp3",
      },
      // {
      //   title: "Sorcery, surely Allah will make it of no effect",
      //   length: '000',
      //   album: "Shaykh Khalid al-Hibsh",
      //   albumImage: "https://upload.wikimedia.org/wikipedia/en/4/48/Pnau_alternate_cover.jpg",
      //   url: "https://s3.eu-central-1.amazonaws.com/ruqyah/sybtluh.mp3",
      // },
      {
        title: "Part 2 of verse 81 of Surat Yunus",
        length: '159',
        album: "Shaykh Khalid al-Hibsh",
        albumImage: "https://upload.wikimedia.org/wikipedia/en/4/48/Pnau_alternate_cover.jpg",
        url: "https://s3.eu-central-1.amazonaws.com/ruqyah/sybtilh-wawhyna.mp3",
      },
      {
        title: "Envy (HASAD) New",
        length: '2430',
        album: "Shaykh Khalid al-Hibsh",
        albumImage: "https://upload.wikimedia.org/wikipedia/en/4/48/Pnau_alternate_cover.jpg",
        url: "https://s3.eu-central-1.amazonaws.com/ruqyah/hasada.mp3",
      },
      {
        title: "Last 2 Ayaat of Surat Al-Baqarah",
        length: '536',
        album: "Shaykh Khalid al-Hibsh",
        albumImage: "https://upload.wikimedia.org/wikipedia/en/4/48/Pnau_alternate_cover.jpg",
        url: "https://s3.eu-central-1.amazonaws.com/ruqyah/aaman.mp3",
      },
      {
        title: "Beginning of Surat As-Saafat",
        length: '140',
        album: "Shaykh Khalid al-Hibsh",
        albumImage: "https://upload.wikimedia.org/wikipedia/en/4/48/Pnau_alternate_cover.jpg",
        url: "https://s3.eu-central-1.amazonaws.com/ruqyah/10saft.mp3",
      },
      {
        title: "Verses related to the Planets & Stars",
        length: '1709',
        album: "Shaykh Khalid al-Hibsh",
        albumImage: "https://upload.wikimedia.org/wikipedia/en/4/48/Pnau_alternate_cover.jpg",
        url: "https://s3.eu-central-1.amazonaws.com/ruqyah/stars.mp3",
      },
      {
        title: "Verses of the Sea",
        length: '2259',
        album: "Shaykh Khalid al-Hibsh",
        albumImage: "https://upload.wikimedia.org/wikipedia/en/4/48/Pnau_alternate_cover.jpg",
        url: "https://s3.eu-central-1.amazonaws.com/ruqyah/sea.mp3",
      },
      {
        title: "Verses related to the Grave",
        length: '897',
        album: "Shaykh Khalid al-Hibsh",
        albumImage: "https://upload.wikimedia.org/wikipedia/en/4/48/Pnau_alternate_cover.jpg",
        url: "https://s3.eu-central-1.amazonaws.com/ruqyah/graves.mp3",
      },
      {
        title: "Ruqya for Breast Cancer",
        length: '3755',
        album: "Shaykh Khalid al-Hibsh",
        albumImage: "https://upload.wikimedia.org/wikipedia/en/4/48/Pnau_alternate_cover.jpg",
        url: "https://s3.eu-central-1.amazonaws.com/ruqyah/canser.mp3",
      },
      {
        title: "Ruqya for Walking Issues",
        length: '1424',
        album: "Shaykh Khalid al-Hibsh",
        albumImage: "https://upload.wikimedia.org/wikipedia/en/4/48/Pnau_alternate_cover.jpg",
        url: "https://s3.eu-central-1.amazonaws.com/ruqyah/walk-leg.mp3",
      }
    ]
  },
]

module.exports = { Author: Author };
